#! /bin/bash

# github 
# ssh -T git@github.com
# ln -s ~/dotfile/.ssh ~/.ssh

# git
ln -s ~/dotfile/git/.gitconfig ~/.gitconfig
ln -s ~/dotfile/git/gitignore_global ~/.gitignore_global

# vim
ln -s ~/dotfile/vim/.vimrc ~/.vimrc
# ln -s ~/dotfile/vim/.ideavimrc ~/.ideavimrc
# ln -s ~/dotfile/vim/vimrc.bundles ~/.vimrc.bundles
# ln -s ~/dotfile/vim/.vim/doc ~/.vim/doc
# ln -s ~/dotfile/vim/.vim/plugin ~/.vim/plugin
# ln -s ~/dotfile/vim/.vim/nerdtree_plugin ~/.vim/nerdtree_plugin
# ln -s ~/dotfile/vim/.vim/syntax ~/.vim/syntax
ln -s ~/dotfile/vim/.vim ~/.vim

# bash_profile
ln -s ~/dotfile/bash/bash_all ~/bash_all

# tmux
# ln -s ~/dotfile/tmux/tmux.conf ~/.tmux.conf

# zsh
# ln -s ~/dotfile/themes/agnoster.zsh-theme ~/.oh-my-zsh/themes/agnoster.zsh-theme

# proxy
# ln -s ~/dotfile/bash/proxy.sh /usr/local/bin/tpx.sh
